const MainContent = () => {
  return (
    <table style={{width:'100%'}}>
      <thead>
        <tr>
          <th>名前</th>
          <th>更新日時</th>
          <th>種類</th>
          <th>サイズ</th>
        </tr>
      </thead>
      <tbody>
        <tr>
          <td>test</td>
          <td>2021/08/11</td>
          <td>ファイル</td>
          <td>20kb</td>
        </tr>
        <tr>
          <td>test</td>
          <td>2021/08/11</td>
          <td>ファイル</td>
          <td>20kb</td>
        </tr>
        <tr>
          <td>test</td>
          <td>2021/08/11</td>
          <td>ファイル</td>
          <td>20kb</td>
        </tr>
        <tr>
          <td>test</td>
          <td>2021/08/11</td>
          <td>ファイル</td>
          <td>20kb</td>
        </tr>
        <tr>
          <td>test</td>
          <td>2021/08/11</td>
          <td>ファイル</td>
          <td>20kb</td>
        </tr>
        <tr>
          <td>test</td>
          <td>2021/08/11</td>
          <td>ファイル</td>
          <td>20kb</td>
        </tr>
      </tbody>
    </tables>
  )
}
export default MainContent
